### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by AlliedToasters** [wgmi-rambo/nft-website#7]
@wgmi-rambo I am getting a failure when I try to build:
`$pipenv run python build.py`
```
cmd ['rollup', '--config', 'rollup.config.js']
[!] Error: Cannot find module '@rollup/plugin-node-resolve'
Require stack:
- /home/alliedtoasters/projects/wgmi/nft-website/rollup.config.js
- /home/alliedtoasters/.nvm/versions/node/v14.17.5/lib/node_modules/rollup/dist/shared/loadConfigFile.js
- /home/alliedtoasters/.nvm/versions/node/v14.17.5/lib/node_modules/rollup/dist/bin/rollup
Error: Cannot find module '@rollup/plugin-node-resolve'
Require stack:
- /home/alliedtoasters/projects/wgmi/nft-website/rollup.config.js
- /home/alliedtoasters/.nvm/versions/node/v14.17.5/lib/node_modules/rollup/dist/shared/loadConfigFile.js
- /home/alliedtoasters/.nvm/versions/node/v14.17.5/lib/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/alliedtoasters/projects/wgmi/nft-website/rollup.config.js:6:25)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.require.extensions.<computed> [as .js] (/home/alliedtoasters/.nvm/versions/node/v14.17.5/lib/node_modules/rollup/dist/shared/loadConfigFile.js:560:20)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)

Build complete.
```

**Comment by AlliedToasters** [comment]
I guess the build actually doesn't fail, but there is an error msg.

**Comment by wgmi-rambo** [comment]
Does doing an npm install solve the issue?

**Comment by wgmi-rambo** [comment]
Any luck?

**Comment by AlliedToasters** [comment]
yeah, a fresh install did the trick :)
